- name: satellite settings | common settings
  theforeman.foreman.setting:
    username: "{{ satellite_admin_username }}"
    password: "{{ satellite_admin_password }}"
    server_url: "{{ satellite_server_url }}"
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  changed_when: false
  with_items:
    - "{{ satellite_settings }}"

- name: satellite settings | disconnected settings
  theforeman.foreman.setting:
    username: "{{ satellite_admin_username }}"
    password: "{{ satellite_admin_password }}"
    server_url: "{{ satellite_server_url }}"
    name: "content_disconnected"
    value: "true"
  changed_when: false
  when: satellite_rhn_connect == 'disconnect'
