# task file for install
- name: main | install theforeman prereq
  import_tasks: 2_theforeman.yml

- name: main | install satellite
  import_tasks: 4_install.yml

- name: main | set satellite settings
  import_tasks: 5_settings.yml
